{"status": "failed", "name": "Sing in with invalid email and password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Sing In"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1556962530661, "historyId": "349a634e6b58b350d7117e4549e65623", "start": 1556962519557, "steps": [{"status": "passed", "start": 1556962519560, "stop": 1556962526046, "name": "Given I navigate to home page"}, {"status": "passed", "start": 1556962526047, "stop": 1556962529087, "name": "When I sing in with email:ruxi and pass: 1234"}, {"status": "passed", "start": 1556962529088, "stop": 1556962530616, "name": "When I press the Sing In button"}, {"status": "failed", "start": 1556962530616, "stop": 1556962530660, "name": "Then Verify if an error message is displayed", "statusDetails": {"message": "AssertionError: The error message is displayed\n", "trace": "  File \"c:\\python27\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\python27\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\sing_in_steps.py\", line 30, in step_impl\n    assert True==SingIn.SingInAuthentication().is_error_message_present(),\"The error message is displayed\"\n"}}], "statusDetails": {"message": "AssertionError: The error message is displayed\n", "trace": "  File \"c:\\python27\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\python27\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\sing_in_steps.py\", line 30, in step_impl\n    assert True==SingIn.SingInAuthentication().is_error_message_present(),\"The error message is displayed\"\n"}, "uuid": "9b71944b-7894-49d0-81ee-45339b53dd87"}